schema: "classroom50/repo-config/v1"
classroom: "advanced-python-programming"
assignment: "kawa"
secret: "ixhtwg93"
owner:
  username: "Gasasiragrace"
  id: 194396886
  accepted_at: "2026-10-01T07:08:16Z"
source:
  owner: "ALU-BSE"
  owner_id: 148322097
  repo: "advanced-python-kawa-template"
  branch: "main"
