# Generated by Django 4.2.30 on 2026-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
