# Generated by Django 4.2.30 on 2026-09-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_priceschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCheckAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('error', 'Error')], max_length=10)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_attempts', to='deliveries.plot')),
            ],
        ),
    ]
